# Data Cleaning

Disclaimer: this notebook has been written with the aid of [ChatGPT](https://chatgpt.com/share/6a25b40f-d42c-83eb-91cc-48ab869c6785).

## Importing the Libraries

In [310]:
# Importing necessary libraries
import pandas as pd
import numpy as np

## Loading Datasets

In [312]:
# Setting paths for the data folder and the orignal data files
dataFolder = "C:/Users/sKALa/Repos/Semester 2/Dissertation/Albert Skalinski - Dissertation/data"
originalData1Path = dataFolder + "/originalData1.csv"
originalData2Path = dataFolder + "/originalData2.csv"

# Reading both .csv files
df1 = pd.read_csv(originalData1Path)
df2 = pd.read_csv(originalData2Path)

# Checking if the data has been read correctly
print("Dataset 1 shape:", df1.shape)
print("Dataset 2 shape:", df2.shape)

Dataset 1 shape: (1686, 29)
Dataset 2 shape: (3145, 29)

In [313]:
# Displaying the first few rows of each dataset
display(df1.head())
display(df2.head())

,energy,tempo,danceability,playlist_genre,loudness,liveness,valence,track_artist,time_signature,speechiness,...,instrumentalness,track_album_id,mode,key,duration_ms,acousticness,id,playlist_subgenre,type,playlist_id
0,0.592,157.969,0.521,pop,-7.777,0.122,0.535,"Lady Gaga, Bruno Mars",3,0.0304,...,0.0000,10FLjwfpbxLmW8c25Xyc2N,0,6,251668,0.3080,2plbrEY59IikOBgBGLjaoe,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
1,0.507,104.978,0.747,pop,-10.171,0.117,0.438,Billie Eilish,4,0.0358,...,0.0608,7aJuG4TFXa2hmE4z1yxc3n,1,2,210373,0.2000,6dOtVTDdiauQNBQEDOtlAB,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
2,0.808,108.548,0.554,pop,-4.169,0.159,0.372,Gracie Abrams,4,0.0368,...,0.0000,0hBRqPYPXhr1RkTDG3n4Mk,1,1,166300,0.2140,7ne4VBA60CxGM75vw0EYad,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
3,0.910,112.966,0.670,pop,-4.070,0.304,0.786,Sabrina Carpenter,4,0.0634,...,0.0000,4B4Elma4nNDUyl6D5PvQkj,0,0,157280,0.0939,1d7Ptw3qYcfpdLNL5REhtJ,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
4,0.783,149.027,0.777,pop,-4.477,0.355,0.939,"ROSÉ, Bruno Mars",4,0.2600,...,0.0000,2IYQwwgxgOIn7t3iF6ufFD,0,0,169917,0.0283,5vNRhkKd0yEAg8suGBpjeY,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M

,time_signature,track_popularity,speechiness,danceability,playlist_name,track_artist,duration_ms,energy,playlist_genre,playlist_subgenre,...,track_album_id,playlist_id,track_id,valence,key,tempo,loudness,acousticness,liveness,track_album_name
0,4.0,23,0.0393,0.636,Rock Classics,Creedence Clearwater Revival,138053.0,0.746,rock,classic,...,4A8gFwqd9jTtnsNwUu3OQx,37i9dQZF1DWXRqgorJj26U,5e6x5YRnMJIKvYpZxLqdpH,0.432,0.0,132.310,-3.785,0.0648,0.1730,The Long Road Home - The Ultimate John Fogerty...
1,4.0,53,0.0317,0.572,Rock Classics,Van Halen,241600.0,0.835,rock,classic,...,2c965LEDRNrXXCeBOAAwns,37i9dQZF1DWXRqgorJj26U,5FqYA8KfiwsQvyBI4IamnY,0.795,0.0,129.981,-6.219,0.1710,0.0702,The Collection
2,4.0,55,0.0454,0.591,Rock Classics,Stevie Nicks,329413.0,0.804,rock,classic,...,3S404OgKoVQSJ3xXrDVlp8,37i9dQZF1DWXRqgorJj26U,5LNiqEqpDc8TuqPy79kDBu,0.658,0.0,111.457,-7.299,0.3270,0.0818,Bella Donna (Deluxe Edition)
3,4.0,64,0.1010,0.443,Jazz Classics,"Ella Fitzgerald, Louis Armstrong",185160.0,0.104,jazz,classic,...,1y5KGkUKO0NG32MhIIagCA,37i9dQZF1DXbITWG1ZJKYt,78MI7mu1LV1k4IA2HzKmHe,0.394,0.0,76.474,-17.042,0.9130,0.1910,"Love, Ella"
4,4.0,62,0.0298,0.685,Jazz Classics,Galt MacDermot,205720.0,0.472,jazz,classic,...,6f4b9wVTkKAf096k4XG6x5,37i9dQZF1DXbITWG1ZJKYt,6MN6yRVriszuyAVlyF8ndB,0.475,9.0,80.487,-9.691,0.7850,0.2240,Shapes of Rhythm/Woman Is Sweeter

## Matching Columns

In [314]:
# The second dataframe has its columns in a different order, so they need to be reordered
df2 = df2[df1.columns]

# Checking applied changes
display(df1.head())
display(df2.head())

,energy,tempo,danceability,playlist_genre,loudness,liveness,valence,track_artist,time_signature,speechiness,...,instrumentalness,track_album_id,mode,key,duration_ms,acousticness,id,playlist_subgenre,type,playlist_id
0,0.592,157.969,0.521,pop,-7.777,0.122,0.535,"Lady Gaga, Bruno Mars",3,0.0304,...,0.0000,10FLjwfpbxLmW8c25Xyc2N,0,6,251668,0.3080,2plbrEY59IikOBgBGLjaoe,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
1,0.507,104.978,0.747,pop,-10.171,0.117,0.438,Billie Eilish,4,0.0358,...,0.0608,7aJuG4TFXa2hmE4z1yxc3n,1,2,210373,0.2000,6dOtVTDdiauQNBQEDOtlAB,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
2,0.808,108.548,0.554,pop,-4.169,0.159,0.372,Gracie Abrams,4,0.0368,...,0.0000,0hBRqPYPXhr1RkTDG3n4Mk,1,1,166300,0.2140,7ne4VBA60CxGM75vw0EYad,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
3,0.910,112.966,0.670,pop,-4.070,0.304,0.786,Sabrina Carpenter,4,0.0634,...,0.0000,4B4Elma4nNDUyl6D5PvQkj,0,0,157280,0.0939,1d7Ptw3qYcfpdLNL5REhtJ,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
4,0.783,149.027,0.777,pop,-4.477,0.355,0.939,"ROSÉ, Bruno Mars",4,0.2600,...,0.0000,2IYQwwgxgOIn7t3iF6ufFD,0,0,169917,0.0283,5vNRhkKd0yEAg8suGBpjeY,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M

,energy,tempo,danceability,playlist_genre,loudness,liveness,valence,track_artist,time_signature,speechiness,...,instrumentalness,track_album_id,mode,key,duration_ms,acousticness,id,playlist_subgenre,type,playlist_id
0,0.746,132.310,0.636,rock,-3.785,0.1730,0.432,Creedence Clearwater Revival,4.0,0.0393,...,0.290000,4A8gFwqd9jTtnsNwUu3OQx,1.0,0.0,138053.0,0.0648,5e6x5YRnMJIKvYpZxLqdpH,classic,audio_features,37i9dQZF1DWXRqgorJj26U
1,0.835,129.981,0.572,rock,-6.219,0.0702,0.795,Van Halen,4.0,0.0317,...,0.000377,2c965LEDRNrXXCeBOAAwns,1.0,0.0,241600.0,0.1710,5FqYA8KfiwsQvyBI4IamnY,classic,audio_features,37i9dQZF1DWXRqgorJj26U
2,0.804,111.457,0.591,rock,-7.299,0.0818,0.658,Stevie Nicks,4.0,0.0454,...,0.000006,3S404OgKoVQSJ3xXrDVlp8,1.0,0.0,329413.0,0.3270,5LNiqEqpDc8TuqPy79kDBu,classic,audio_features,37i9dQZF1DWXRqgorJj26U
3,0.104,76.474,0.443,jazz,-17.042,0.1910,0.394,"Ella Fitzgerald, Louis Armstrong",4.0,0.1010,...,0.000000,1y5KGkUKO0NG32MhIIagCA,1.0,0.0,185160.0,0.9130,78MI7mu1LV1k4IA2HzKmHe,classic,audio_features,37i9dQZF1DXbITWG1ZJKYt
4,0.472,80.487,0.685,jazz,-9.691,0.2240,0.475,Galt MacDermot,4.0,0.0298,...,0.284000,6f4b9wVTkKAf096k4XG6x5,0.0,9.0,205720.0,0.7850,6MN6yRVriszuyAVlyF8ndB,classic,audio_features,37i9dQZF1DXbITWG1ZJKYt

# Combining Datasets

In [315]:
# Combining both datasets into one
df = pd.concat([df1, df2], ignore_index = True)

# Checking for changes
display(df.shape)
display(df.head())

(4831, 29)

,energy,tempo,danceability,playlist_genre,loudness,liveness,valence,track_artist,time_signature,speechiness,...,instrumentalness,track_album_id,mode,key,duration_ms,acousticness,id,playlist_subgenre,type,playlist_id
0,0.592,157.969,0.521,pop,-7.777,0.122,0.535,"Lady Gaga, Bruno Mars",3.0,0.0304,...,0.0000,10FLjwfpbxLmW8c25Xyc2N,0.0,6.0,251668.0,0.3080,2plbrEY59IikOBgBGLjaoe,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
1,0.507,104.978,0.747,pop,-10.171,0.117,0.438,Billie Eilish,4.0,0.0358,...,0.0608,7aJuG4TFXa2hmE4z1yxc3n,1.0,2.0,210373.0,0.2000,6dOtVTDdiauQNBQEDOtlAB,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
2,0.808,108.548,0.554,pop,-4.169,0.159,0.372,Gracie Abrams,4.0,0.0368,...,0.0000,0hBRqPYPXhr1RkTDG3n4Mk,1.0,1.0,166300.0,0.2140,7ne4VBA60CxGM75vw0EYad,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
3,0.910,112.966,0.670,pop,-4.070,0.304,0.786,Sabrina Carpenter,4.0,0.0634,...,0.0000,4B4Elma4nNDUyl6D5PvQkj,0.0,0.0,157280.0,0.0939,1d7Ptw3qYcfpdLNL5REhtJ,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
4,0.783,149.027,0.777,pop,-4.477,0.355,0.939,"ROSÉ, Bruno Mars",4.0,0.2600,...,0.0000,2IYQwwgxgOIn7t3iF6ufFD,0.0,0.0,169917.0,0.0283,5vNRhkKd0yEAg8suGBpjeY,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M

## Resolving Missing Values

In [316]:
# Checking for missing values
missingValues = df.isna().sum()
display(missingValues)

energy                      1
tempo                       1
danceability                1
playlist_genre              0
loudness                    1
liveness                    1
valence                     1
track_artist                0
time_signature              1
speechiness                 1
track_popularity            0
track_href                  1
uri                         1
track_album_name            1
playlist_name               0
analysis_url                1
track_id                    0
track_name                  0
track_album_release_date    0
instrumentalness            1
track_album_id              0
mode                        1
key                         1
duration_ms                 1
acousticness                1
id                          1
playlist_subgenre           0
type                        1
playlist_id                 0
dtype: int64

In [317]:
# Removing rows with missing values, since they're marginal compared to the size of the dataset
df.dropna(inplace = True)

## Resolving Duplicates

In [318]:
# Checking for exact duplicates
exactDuplicates = df.duplicated().sum()

print("Number of exact duplicate rows:", exactDuplicates)

Number of exact duplicate rows: 43

In [319]:
# Removing the duplicates
df = df.drop_duplicates()

# Checking for applied changes
print(df.shape)

(4786, 29)

In [320]:
# Checking for duplicate track IDs
duplicateTrackIDs = df["track_id"].duplicated().sum()

print("Number of duplicate track IDs:", duplicateTrackIDs)

Number of duplicate track IDs: 293

In [321]:
# Removing duplicate track IDs, keeping only the first occurrence

df = df.drop_duplicates(subset = "track_id", keep = "first")
df = df.reset_index(drop = True)

print("Shape after removing duplicate track IDs:", df.shape)
print("Remaining duplicate IDs:", df["track_id"].duplicated().sum())

Shape after removing duplicate track IDs: (4493, 29)
Remaining duplicate IDs: 0

## Checking Datatypes

In [322]:
# Checking datatypes
print(df.dtypes)

energy                      float64
tempo                       float64
danceability                float64
playlist_genre               object
loudness                    float64
liveness                    float64
valence                     float64
track_artist                 object
time_signature              float64
speechiness                 float64
track_popularity              int64
track_href                   object
uri                          object
track_album_name             object
playlist_name                object
analysis_url                 object
track_id                     object
track_name                   object
track_album_release_date     object
instrumentalness            float64
track_album_id               object
mode                        float64
key                         float64
duration_ms                 float64
acousticness                float64
id                           object
playlist_subgenre            object
type                         object
playlist_id                  object
dtype: object

In [323]:
# Changing some of the types into ints to better match the data they represent
df["time_signature"] = df["time_signature"].astype(int)
df["track_popularity"] = df["track_popularity"].astype(int)
df["mode"] = df["mode"].astype(int)
df["key"] = df["key"].astype(int)
df["duration_ms"] = df["duration_ms"].astype(int)

# Checking applied changes
print(df.dtypes)

energy                      float64
tempo                       float64
danceability                float64
playlist_genre               object
loudness                    float64
liveness                    float64
valence                     float64
track_artist                 object
time_signature                int64
speechiness                 float64
track_popularity              int64
track_href                   object
uri                          object
track_album_name             object
playlist_name                object
analysis_url                 object
track_id                     object
track_name                   object
track_album_release_date     object
instrumentalness            float64
track_album_id               object
mode                          int64
key                           int64
duration_ms                   int64
acousticness                float64
id                           object
playlist_subgenre            object
type                         object
playlist_id                  object
dtype: object

In [324]:
# Making duration cleaner by converting it from milliseconds to minutes to two decimal places
df["duration_min"] = df["duration_ms"] / 60000
df["duration_min"] = df["duration_min"].round(2)

## Handling Release Date

In [325]:
# Parsing release dates
df["track_album_release_date_original"] = df["track_album_release_date"]
df["track_album_release_date"] = pd.to_datetime(df["track_album_release_date"], errors = "coerce")

# The print statement below indicates all the fields that have a year only instead of a full date
print("Missing parsed release dates:", df["track_album_release_date"].isna().sum())

Missing parsed release dates: 125

In [326]:
# Adding additional columns for release year and month for further analysis
df["release_year"] = df["track_album_release_date"].dt.year
df["release_month"] = df["track_album_release_date"].dt.month

In [327]:
# Removing rows with invalid release years
df = df.dropna(subset = ["release_year"])

In [328]:
# Casting the above columns to int after dropping NaN values
df["release_year"] = df["release_year"].astype(int)
df["release_month"] = df["release_month"].astype(int)

In [329]:
# Creating a time period column for further analysis
def assignTimePeriod(year):
    if year < 1980:
        return "pre-1980"
    elif year < 1990:
        return "1980s"
    elif year < 2000:
        return "1990s"
    elif year < 2010:
        return "2000s"
    elif year < 2020:
        return "2010s"
    else:
        return "2020s"

df["time_period"] = df["release_year"].apply(assignTimePeriod)

## Removing Unnecessary Columns

In [330]:
# Removing columns that were found unncessary for the analysis and provided no useful information
df = df.drop(columns = ["track_href", "uri", "playlist_name", "analysis_url", "track_album_id", "id", "playlist_subgenre", "type",
            "playlist_id", "track_album_name", "track_album_release_date_original", "release_decade", "track_id", "duration_ms"], errors = "ignore")

# Checking for applied changes
display(df.head(10))

,energy,tempo,danceability,playlist_genre,loudness,liveness,valence,track_artist,time_signature,speechiness,...,track_name,track_album_release_date,instrumentalness,mode,key,acousticness,duration_min,release_year,release_month,time_period
0,0.592,157.969,0.521,pop,-7.777,0.1220,0.535,"Lady Gaga, Bruno Mars",3,0.0304,...,Die With A Smile,2024-08-16,0.000000,0,6,0.3080,4.19,2024,8,2020s
1,0.507,104.978,0.747,pop,-10.171,0.1170,0.438,Billie Eilish,4,0.0358,...,BIRDS OF A FEATHER,2024-05-17,0.060800,1,2,0.2000,3.51,2024,5,2020s
2,0.808,108.548,0.554,pop,-4.169,0.1590,0.372,Gracie Abrams,4,0.0368,...,That’s So True,2024-10-18,0.000000,1,1,0.2140,2.77,2024,10,2020s
3,0.910,112.966,0.670,pop,-4.070,0.3040,0.786,Sabrina Carpenter,4,0.0634,...,Taste,2024-08-23,0.000000,0,0,0.0939,2.62,2024,8,2020s
4,0.783,149.027,0.777,pop,-4.477,0.3550,0.939,"ROSÉ, Bruno Mars",4,0.2600,...,APT.,2024-10-18,0.000000,0,0,0.0283,2.83,2024,10,2020s
5,0.582,116.712,0.700,pop,-5.960,0.0881,0.785,Chappell Roan,4,0.0356,...,"Good Luck, Babe!",2024-04-05,0.000000,0,11,0.0502,3.64,2024,4,2020s
6,0.561,150.069,0.669,pop,-6.538,0.0954,0.841,Addison Rae,4,0.0411,...,Diet Pepsi,2024-08-09,0.009620,1,10,0.4950,2.83,2024,8,2020s
7,0.247,148.101,0.467,pop,-12.002,0.1700,0.126,Billie Eilish,4,0.0431,...,WILDFLOWER,2024-05-17,0.000271,0,6,0.6120,4.36,2024,5,2020s
8,0.416,94.926,0.492,pop,-10.439,0.2030,0.297,Gigi Perez,4,0.0254,...,Sailor Song,2024-07-26,0.000086,1,11,0.6860,3.53,2024,7,2020s
9,0.722,119.973,0.769,pop,-5.485,0.1110,0.570,"The Weeknd, Playboi Carti",4,0.0507,...,Timeless (with Playboi Carti),2024-09-27,0.000003,0,11,0.0584,4.27,2024,9,2020s

## Reordering Columns

In [331]:
# Reordering columns for clarity purposes
orderedColumns = [
    "track_name",
    "track_artist",
    "playlist_genre",
    "track_popularity",
    "track_album_release_date",
    "release_year",
    "release_month",
    "time_period",

    "energy",
    "danceability",
    "loudness",
    "liveness",
    "valence",
    "speechiness",
    "instrumentalness",
    "acousticness",

    "tempo",
    "time_signature",
    "mode",
    "key",
    "duration_min"]

df = df[orderedColumns]

df.head()

,track_name,track_artist,playlist_genre,track_popularity,track_album_release_date,release_year,release_month,time_period,energy,danceability,...,liveness,valence,speechiness,instrumentalness,acousticness,tempo,time_signature,mode,key,duration_min
0,Die With A Smile,"Lady Gaga, Bruno Mars",pop,100,2024-08-16,2024,8,2020s,0.592,0.521,...,0.122,0.535,0.0304,0.0000,0.3080,157.969,3,0,6,4.19
1,BIRDS OF A FEATHER,Billie Eilish,pop,97,2024-05-17,2024,5,2020s,0.507,0.747,...,0.117,0.438,0.0358,0.0608,0.2000,104.978,4,1,2,3.51
2,That’s So True,Gracie Abrams,pop,93,2024-10-18,2024,10,2020s,0.808,0.554,...,0.159,0.372,0.0368,0.0000,0.2140,108.548,4,1,1,2.77
3,Taste,Sabrina Carpenter,pop,81,2024-08-23,2024,8,2020s,0.910,0.670,...,0.304,0.786,0.0634,0.0000,0.0939,112.966,4,0,0,2.62
4,APT.,"ROSÉ, Bruno Mars",pop,98,2024-10-18,2024,10,2020s,0.783,0.777,...,0.355,0.939,0.2600,0.0000,0.0283,149.027,4,0,0,2.83

## Chaning Column Names

In [332]:
# Changing the names for clarity purposes
df.rename(columns = {
    "track_name": "name",
    "track_artist": "artist",
    # playlist genre simplified to genre since all the songs in the dataset are from playlists and the genre is the same as the playlist genre
    "playlist_genre": "genre",
    "track_popularity": "popularity",
    # album release date simplified to release date since the dataset only contains album tracks and the release date
    #  is the same as the album release date
    "track_album_release_date": "releaseDate",
    "release_year": "releaseYear",
    "release_month": "releaseMonth",
    "time_period": "timePeriod",

    "energy": "energy",
    "danceability": "danceability",
    "loudness": "loudness",
    "liveness": "liveness",
    "valence": "valence",
    "speechiness": "speechiness",
    "instrumentalness": "instrumentalness",
    "acousticness": "acousticness",

    "tempo": "tempo",
    "time_signature": "timeSignature",
    "mode": "mode",
    "key": "key",
    "duration_min": "durationMin"}, inplace = True)

# Checking for applied changes
display(df.head())

,name,artist,genre,popularity,releaseDate,releaseYear,releaseMonth,timePeriod,energy,danceability,...,liveness,valence,speechiness,instrumentalness,acousticness,tempo,timeSignature,mode,key,durationMin
0,Die With A Smile,"Lady Gaga, Bruno Mars",pop,100,2024-08-16,2024,8,2020s,0.592,0.521,...,0.122,0.535,0.0304,0.0000,0.3080,157.969,3,0,6,4.19
1,BIRDS OF A FEATHER,Billie Eilish,pop,97,2024-05-17,2024,5,2020s,0.507,0.747,...,0.117,0.438,0.0358,0.0608,0.2000,104.978,4,1,2,3.51
2,That’s So True,Gracie Abrams,pop,93,2024-10-18,2024,10,2020s,0.808,0.554,...,0.159,0.372,0.0368,0.0000,0.2140,108.548,4,1,1,2.77
3,Taste,Sabrina Carpenter,pop,81,2024-08-23,2024,8,2020s,0.910,0.670,...,0.304,0.786,0.0634,0.0000,0.0939,112.966,4,0,0,2.62
4,APT.,"ROSÉ, Bruno Mars",pop,98,2024-10-18,2024,10,2020s,0.783,0.777,...,0.355,0.939,0.2600,0.0000,0.0283,149.027,4,0,0,2.83

## Saving the Clean Dataset

In [333]:
# Saving the dataset to .csv
cleanedDataPath = dataFolder + "/cleanData.csv"
df.to_csv(cleanedDataPath, index = False)